import os

OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
OPENROUTER_API_KEY_ENV = "OPENROUTER_API_KEY"

CHALLENGER_MODEL = "openai/gpt-5.6-luna"
VERIFIER_MODEL = "openai/gpt-5.6-luna"

STRONG_ARM_MODEL = "z-ai/glm-5.2"
STRONG_ARM_MAX_TOKENS = 4000
STRONG_ARM_TEMPERATURE_RANGE = (0.2, 0.6)
STRONG_ARM_REASONING_ENABLED = False

WEAK_ARM_MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"
WEAK_ARM_MAX_NEW_TOKENS = 4000
WEAK_ARM_TEMPERATURE_RANGE = (0.2, 0.6)
WEAK_ARM_TOP_P = 0.8
WEAK_ARM_TOP_K = 20
WEAK_ARM_MIN_P = 0.0
WEAK_ARM_PRESENCE_PENALTY = 1.5
WEAK_ARM_REPETITION_PENALTY = 1.0

FEEDBACK_TEMPERATURE = 0.3
FEEDBACK_MAX_TOKENS = 4000

WEAK_ARM_ROLLOUTS = 4
STRONG_ARM_ROLLOUTS = 4
WEAK_ARM_MAX_PASS = 1
STRONG_ARM_MIN_PASS = 3

MAX_REFINEMENT_ROUNDS = 10

PROMPTS_DIR = os.path.join(os.path.dirname(__file__), "prompts")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
